version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: 487842886099
    AWS_DEFAULT_REGION: ap-northeast-1
    IMAGE_TAG: latest
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - BASE_DIR=`pwd`
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
  build:
    commands:
      - echo "Building Chat Backend!"
      - mvn clean package -Dmaven.test.skip=true
      - ls -la
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/chat:$IMAGE_TAG .
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/chat:$IMAGE_TAG
      - cd $BASE_DIR
      - printf '[{"name":"chat","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/chat:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json