version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: 487842886099
    AWS_DEFAULT_REGION: ap-northeast-1
    IMAGE_TAG: latest
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - BASE_DIR=`pwd`
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
  build:
    commands:
      - echo "STG -> PROD"
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/stg-chat:$IMAGE_TAG
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/stg-chat:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/chat:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/chat:$IMAGE_TAG
      - echo "PUSH COMPLETED!"
      - printf '[{"Version":"1.0","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/chat:$IMAGE_TAG > imageDetail.json
      - printf '[{"name":"prod--chat-use-alb","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/stg-chat:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imageDetail.json
    - imagedefinitions.json