version: '2'

services:
  db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'chat'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:mysql://db/chat?autoReconnect=true&useSSL=false&serverTimezone=JST
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
    depends_on:
      - db