version: '2'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    extra_hosts:
      - 'home.kadono.work:127.0.0.1'
    links:
      - app
    # restart: always
    environment:
      DOMAINS: 'home.kadono.work -> http://app:8080'
      STAGE: 'production'
      WEBSOCKET: 'true'
      # FORCE_RENEW: 'true'
      # CLIENT_MAX_BODY_SIZE: 0  # これだと無制限
      # CLIENT_MAX_BODY_SIZE: 10M # とか
    volumes:
      - ./org-chimata-ssl-certs:/var/lib/https-portal

  db:
    image: mysql:8.0.17
    environment:
      MYSQL_DATABASE: 'chat'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://db/chat?useUnicode=true&userJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      spring.datasource.username: "user"
      spring.datasource.password: "password"
    depends_on:
      - db
