spring:
  datasource:
    url: jdbc:mysql://db:3306/chat?useUnicode=true&userJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: password
    driverClassName: com.mysql.jdbc.Driver

  thymeleaf:
    mode: HTML

mybatis:
  configuration:
    map-underscore-to-camel-case: true


#############################################################################
############################# Custom Properties #############################
#############################################################################

chat:
  log:
    limit: 10

cookie-name:
  userCookie: UCFSM # User Cookie For Session Management