spring:
  datasource:
    url: jdbc:mysql://ip-172-31-43-239.ap-northeast-1.compute.internal:3306/chat?useUnicode=true&userJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  thymeleaf:
    mode: HTML

server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

mybatis:
  configuration:
    map-underscore-to-camel-case: true


#############################################################################
############################# Custom Properties #############################
#############################################################################

chat:
  log:
    limit: 10

cookie-name:
  userCookie: UCFSM # User Cookie For Session Management